/** Managed-file header marking projen ownership (mirrors projen's own marker). */
export const MANAGED_HEADER =
  '# ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".';

/** Split a provider value into source + version. `source@version` or bare version. */
function splitProvider(name: string, value: string): { source: string; version: string } {
  if (value.includes('@')) {
    const [source, version] = value.split('@');
    return { source, version };
  }
  return { source: `hashicorp/${name}`, version: value };
}

/**
 * Render `versions.tf`. Pure and deterministic: providers are emitted in sorted
 * key order so the output is stable regardless of input ordering (NFR-2 / PBT).
 */
export function renderVersionsTf(opts: {
  terraformVersion: string;
  providers: Record<string, string>;
}): string {
  const names = Object.keys(opts.providers).sort();
  const providerBlocks = names
    .map((name) => {
      const { source, version } = splitProvider(name, opts.providers[name]);
      return [
        `    ${name} = {`,
        `      source  = "${source}"`,
        `      version = "${version}"`,
        '    }',
      ].join('\n');
    })
    .join('\n');

  return [
    MANAGED_HEADER,
    'terraform {',
    `  required_version = "${opts.terraformVersion}"`,
    '  required_providers {',
    providerBlocks,
    '  }',
    '}',
    '',
  ].join('\n');
}
