import { IConstruct } from 'constructs';
import { TextFile } from 'projen';
import { ResolvedOptions } from '../options';

const HEADER =
  '# ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".';

/** Emit a workflow YAML file (managed, our header, not readonly so CI tools can touch). */
function workflow(scope: IConstruct, name: string, lines: string[]): void {
  new TextFile(scope, `.github/workflows/${name}.yml`, {
    marker: false,
    readonly: false,
    lines: [HEADER, ...lines],
  });
}

/** Steps that install all CLI tools onto PATH via setup actions (pinned). */
function setupToolSteps(opts: ResolvedOptions): string[] {
  const steps: string[] = [
    '      - name: Setup Terraform',
    '        uses: hashicorp/setup-terraform@v3',
    '        with:',
    `          terraform_version: "${opts.toolVersions.terraform}"`,
    '          terraform_wrapper: false',
    '      - name: Setup tflint',
    '        uses: terraform-linters/setup-tflint@v4',
    '        with:',
    `          tflint_version: "${opts.toolVersions.tflint}"`,
    '      - name: Setup terraform-docs',
    '        uses: terraform-docs/gh-actions@v1',
    '        with:',
    '          working-dir: .',
    '          output-file: README.md',
    '          output-method: inject',
    '          git-push: "false"',
  ];
  if (opts.securityScanner === 'tfsec' || opts.securityScanner === 'both') {
    steps.push(
      '      - name: Setup tfsec',
      '        run: |',
      `          curl -sSLo /usr/local/bin/tfsec https://github.com/aquasecurity/tfsec/releases/download/${opts.toolVersions.tfsec}/tfsec-linux-amd64`,
      '          chmod +x /usr/local/bin/tfsec',
    );
  }
  if (opts.securityScanner === 'checkov' || opts.securityScanner === 'both') {
    steps.push(
      '      - name: Setup checkov',
      '        run: pipx install checkov==' + opts.toolVersions.checkov,
    );
  }
  return steps;
}

/**
 * `build.yml` — runs the pipeline then self-mutates for terraform-docs + fmt
 * changes only (Q5), uploading a patch that a dependent job applies and pushes
 * via PROJEN_GITHUB_TOKEN (SECURITY-13). Minimal permissions (SECURITY-06).
 */
export function addBuildWorkflow(scope: IConstruct, opts: ResolvedOptions): void {
  workflow(scope, 'build', [
    'name: build',
    'on:',
    '  pull_request: {}',
    '  workflow_dispatch: {}',
    'jobs:',
    '  build:',
    '    runs-on: ubuntu-latest',
    '    permissions:',
    '      contents: read',
    '    outputs:',
    '      self_mutation_happened: ${{ steps.self_mutation.outputs.self_mutation_happened }}',
    '    steps:',
    '      - name: Checkout',
    '        uses: actions/checkout@v4',
    '        with:',
    '          ref: ${{ github.event.pull_request.head.ref }}',
    '          repository: ${{ github.event.pull_request.head.repo.full_name }}',
    ...setupToolSteps(opts),
    '      - name: Format',
    '        run: terraform fmt -recursive',
    '      - name: Validate',
    '        run: terraform init -backend=false -input=false && terraform validate',
    '      - name: Lint',
    '        run: tflint --init && tflint --recursive',
    '      - name: Security scan',
    '        run: |',
    ...(opts.securityScanner === 'tfsec' || opts.securityScanner === 'both'
      ? ['          tfsec .']
      : []),
    ...(opts.securityScanner === 'checkov' || opts.securityScanner === 'both'
      ? ['          checkov -d . --quiet']
      : []),
    '      - name: Find mutations',
    '        id: self_mutation',
    '        run: |-',
    '          git add .',
    '          git diff --staged --patch --exit-code > repo.patch || echo "self_mutation_happened=true" >> $GITHUB_OUTPUT',
    '        shell: bash',
    '      - name: Upload patch',
    '        if: steps.self_mutation.outputs.self_mutation_happened',
    '        uses: actions/upload-artifact@v4',
    '        with:',
    '          name: repo.patch',
    '          path: repo.patch',
    '          overwrite: true',
    '      - name: Fail build on mutation',
    '        if: steps.self_mutation.outputs.self_mutation_happened',
    '        run: |-',
    '          echo "::error::Files were changed during build (terraform-docs/fmt). Commit the changes."',
    '          cat repo.patch',
    '          exit 1',
    '  self-mutation:',
    '    needs: build',
    '    runs-on: ubuntu-latest',
    '    permissions:',
    '      contents: write',
    '    if: always() && needs.build.outputs.self_mutation_happened && !(github.event.pull_request.head.repo.full_name != github.repository)',
    '    steps:',
    '      - name: Checkout',
    '        uses: actions/checkout@v4',
    '        with:',
    '          token: ${{ secrets.PROJEN_GITHUB_TOKEN }}',
    '          ref: ${{ github.event.pull_request.head.ref }}',
    '          repository: ${{ github.event.pull_request.head.repo.full_name }}',
    '      - name: Download patch',
    '        uses: actions/download-artifact@v4',
    '        with:',
    '          name: repo.patch',
    '          path: ${{ runner.temp }}',
    '      - name: Apply patch',
    '        run: \'[ -s ${{ runner.temp }}/repo.patch ] && git apply ${{ runner.temp }}/repo.patch || echo "Empty patch. Skipping."\'',
    '      - name: Set git identity',
    '        run: |-',
    '          git config user.name "github-actions[bot]"',
    '          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"',
    '      - name: Push changes',
    '        env:',
    '          PULL_REQUEST_REF: ${{ github.event.pull_request.head.ref }}',
    '        run: |-',
    '          git add .',
    '          git commit -s -m "chore: self mutation"',
    '          git push origin "HEAD:$PULL_REQUEST_REF"',
  ]);
}

/**
 * `upgrade.yml` — nightly + dispatch. Bumps tool versions and provider pins by
 * re-running projen, then opens a PR (peter-evans). Matches CDK upgrade shape.
 */
export function addUpgradeWorkflow(scope: IConstruct, _opts: ResolvedOptions): void {
  workflow(scope, 'upgrade', [
    'name: upgrade',
    'on:',
    '  workflow_dispatch: {}',
    '  schedule:',
    '    - cron: "0 0 * * *"',
    'jobs:',
    '  upgrade:',
    '    name: Upgrade tools and providers',
    '    runs-on: ubuntu-latest',
    '    permissions:',
    '      contents: read',
    '    outputs:',
    '      patch_created: ${{ steps.create_patch.outputs.patch_created }}',
    '    steps:',
    '      - name: Checkout',
    '        uses: actions/checkout@v4',
    '      - name: Setup Node',
    '        uses: actions/setup-node@v4',
    '        with:',
    '          node-version: "22"',
    '      - name: Install dependencies',
    '        run: npm ci',
    '      - name: Upgrade (tools + provider pins)',
    '        run: npx projen upgrade',
    '      - name: Find mutations',
    '        id: create_patch',
    '        run: |-',
    '          git add .',
    '          git diff --staged --patch --exit-code > repo.patch || echo "patch_created=true" >> $GITHUB_OUTPUT',
    '        shell: bash',
    '      - name: Upload patch',
    '        if: steps.create_patch.outputs.patch_created',
    '        uses: actions/upload-artifact@v4',
    '        with:',
    '          name: repo.patch',
    '          path: repo.patch',
    '          overwrite: true',
    '  pr:',
    '    name: Create Pull Request',
    '    needs: upgrade',
    '    runs-on: ubuntu-latest',
    '    permissions:',
    '      contents: read',
    '    if: ${{ needs.upgrade.outputs.patch_created }}',
    '    steps:',
    '      - name: Checkout',
    '        uses: actions/checkout@v4',
    '      - name: Download patch',
    '        uses: actions/download-artifact@v4',
    '        with:',
    '          name: repo.patch',
    '          path: ${{ runner.temp }}',
    '      - name: Apply patch',
    '        run: \'[ -s ${{ runner.temp }}/repo.patch ] && git apply ${{ runner.temp }}/repo.patch || echo "Empty patch. Skipping."\'',
    '      - name: Create Pull Request',
    '        uses: peter-evans/create-pull-request@v7',
    '        with:',
    '          token: ${{ secrets.PROJEN_GITHUB_TOKEN }}',
    '          commit-message: "chore(deps): upgrade terraform tools and providers"',
    '          branch: github-actions/upgrade',
    '          title: "chore(deps): upgrade terraform tools and providers"',
    '          body: "Automated upgrade of tool versions and provider pins via the upgrade workflow."',
    '          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"',
    '          committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"',
    '          signoff: true',
  ]);
}

/** `pull-request-lint.yml` — semantic PR title validation. */
export function addPullRequestLintWorkflow(scope: IConstruct): void {
  workflow(scope, 'pull-request-lint', [
    'name: pull-request-lint',
    'on:',
    '  pull_request_target:',
    '    types:',
    '      - labeled',
    '      - opened',
    '      - synchronize',
    '      - reopened',
    '      - ready_for_review',
    '      - edited',
    '  merge_group: {}',
    'jobs:',
    '  validate:',
    '    name: Validate PR title',
    '    runs-on: ubuntu-latest',
    '    permissions:',
    '      pull-requests: write',
    "    if: (github.event_name == 'pull_request' || github.event_name == 'pull_request_target')",
    '    steps:',
    '      - uses: amannn/action-semantic-pull-request@v6',
    '        env:',
    '          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}',
    '        with:',
    '          types: |-',
    '            feat',
    '            fix',
    '            chore',
    '          requireScope: false',
  ]);
}

/** Add all three workflows. */
export function addWorkflows(scope: IConstruct, opts: ResolvedOptions): void {
  addBuildWorkflow(scope, opts);
  addUpgradeWorkflow(scope, opts);
  addPullRequestLintWorkflow(scope);
}
